const flowbiteReact = require("flowbite-react/plugin/tailwindcss");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
    "node_modules/flowbite-react/**/*.{js,jsx,ts,tsx}",
    ".flowbite-react/class-list.json"
  ],
  darkMode: "class",
  theme: {
    colors: {
      primary: {
        50: "#eff6ff",
        100: "#dbeafe",
        200: "#bfdbfe",
        300: "#93c5fd",
        400: "#60a5fa",
        500: "#3b82f6",
        600: "#2563eb",
        700: "#1d4ed8",
        800: "#1e40af",
        900: "#1e3a8a",
      },
    },
    fontFamily: {
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      mono: [
        "ui-monospace",
        "SFMono-Regular",
        "Menlo",
        "Monaco",
        "Consolas",
        "Liberation Mono",
        "Courier New",
        "monospace",
      ],
    },
    extend: {},
  },
  plugins: [require("flowbite/plugin"), flowbiteReact],
  safelist: [
    "bg-white",
    "dark:bg-gray-700",
    "text-gray-500",
    "dark:text-gray-400",
    "border-0",
    "rounded-lg",
    "shadow-lg",
    "py-2",
    "px-4",
    "bg-gray-100",
    "dark:bg-gray-600",
    "border-b",
    "border-gray-200",
    "dark:border-gray-500",
    "text-gray-300",
    "text-gray-900",
    "dark:text-white",
    "font-semibold",
    "text-sm",
    "mt-0",
    "text-left",
    "font-normal",
    "fill-[#4B5563]",
    "opacity-0",
    "transition-opacity",
    "duration-300",
    "dark:bg-gray-800",
    "bg-gray-50",
    "hover:bg-gray-100",
    "dark:hover:bg-gray-800",
    "gap-2",
    "bg-blue-700",
    "hover:bg-blue-800",
    "focus:ring-4",
    "focus:ring-blue-300",
    "dark:bg-blue-600",
    "dark:hover:bg-blue-700",
    "dark:focus:ring-blue-800",
    "font-medium",
    "rounded-lg",
    "text-sm",
    "focus:outline-none",
    "inline-flex",
    "items-center",
    "justify-center",
    "px-5",
    "py-2.5",
    "text-center",
  ],
};